from playwright.sync_api import sync_playwright
from pathlib import Path
import json, os, shutil
R=Path(__file__).resolve().parents[1];O=R/'verification';O.mkdir(exist_ok=True)
checks=[]
def check(name,ok):
 checks.append({'check':name,'passed':bool(ok)})
 if not ok:raise AssertionError(name)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium') or shutil.which('google-chrome'),headless=True,args=['--no-sandbox'] if os.environ.get('ALLOW_UNSANDBOXED_LOCAL_FIXTURE')=='1' else [])
 page=browser.new_page(viewport={'width':1440,'height':1100},device_scale_factor=1)
 errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content((R/'design/preview.html').read_text(),wait_until='load')
 check('initial 4 case buttons',page.locator('[data-case]').count()==4)
 check('no desktop horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
 page.screenshot(path=str(O/'design-desktop.png'),full_page=True)
 page.get_by_label('Search synthetic cases').fill('Modewerk');check('search filters case list',page.locator('[data-case]').count()==1)
 page.get_by_label('Search synthetic cases').fill('not-a-case');check('empty filter recovery visible',page.locator('#clear-filters').is_visible())
 page.locator('#clear-filters').click();check('clear restores list',page.locator('[data-case]').count()==4)
 page.locator('[data-filter="ready"]').click();check('ready filter count',page.locator('[data-case]').count()==1)
 page.locator('[data-filter="all"]').click()
 page.locator('#tab-source').click();check('source selected',page.locator('#tab-source').get_attribute('aria-pressed')=='true')
 page.locator('#zoom-open').click();check('artifact dialog opens',page.locator('#zoom-dialog').is_visible());page.keyboard.press('Escape');check('escape closes artifact dialog',not page.locator('#zoom-dialog').is_visible())
 page.locator('#confirm').click();check('reason required',page.locator('#review-message').inner_text().startswith('Add a brief reason'))
 page.locator('#review-note').fill('Reviewed the two local fixture responses; no merchant or sales inference.')
 page.locator('#confirm').click();check('local confirmation changes state',page.locator('#finding-status').inner_text().startswith('CONFIRMED LOCALLY'))
 check('report unlocked only after confirmation',page.locator('#report-open').is_enabled())
 page.locator('#report-open').click();check('report shows reviewer note', 'two local fixture' in page.locator('#report-note').inner_text());page.keyboard.press('Escape')
 page.locator('#reset').click();page.locator('#review-note').fill('The evidence is not sufficient for a commercial conclusion.')
 page.locator('#reject').click();check('rejected case cannot report',page.locator('#report-open').is_disabled())
 page.locator('#reset').click();page.locator('[data-case="023"]').click();check('missing artifact honest state',page.locator('.unavailable').is_visible());check('unknown cannot be confirmed',page.locator('#confirm').is_disabled())
 page.locator('[data-case="022"]').click();check('challenge remains unknown',page.locator('#finding-status').inner_text().startswith('UNKNOWN'))
 page.screenshot(path=str(O/'design-blocked.png'),full_page=True)
 page.locator('#scan-open').click();check('live scan explicitly disabled',page.get_by_role('button',name='Start live scan',exact=True).is_disabled())
 page.locator('#inspect-fixture').click();check('fixture action opens first case',page.locator('#case-name').inner_text()=='Atelier Nord')
 page.locator('#notes-open').click();check('design mandate available',page.locator('#notes-dialog').is_visible());page.keyboard.press('Escape')
 page.locator('#reset').click();page.keyboard.press('Tab');check('keyboard focus reaches element',page.evaluate('document.activeElement !== document.body'))
 page.screenshot(path=str(O/'design-desktop.png'),full_page=True)
 for w in [1024,768,390,320]:
  page.set_viewport_size({'width':w,'height':900});check(f'no horizontal overflow at {w}',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
  if w==390:
   check('mobile queue initially compact',not page.locator('#index-body').is_visible())
   page.locator('#index-toggle').click();check('mobile queue opens',page.locator('#index-body').is_visible())
   page.locator('[data-case="024"]').click();check('select returns to compact case',not page.locator('#index-body').is_visible())
   check('mobile evidence control target',page.locator('#tab-source').bounding_box()['height']>=44)
   page.screenshot(path=str(O/'design-mobile.png'),full_page=True)
 page.emulate_media(reduced_motion='reduce');check('reduced-motion mode renders',page.locator('#case-name').is_visible())
 check('no javascript exceptions',len(errors)==0)
 browser.close()
(O/'preview-checks.json').write_text(json.dumps({'environment':'Chromium; inline HTML loaded with set_content; local browser navigation unavailable. These are prototype interaction checks, not app end-to-end tests.','checks':checks,'js_errors':errors},indent=2))
print(len(checks),'prototype checks passed')
