import test from 'node:test';import assert from 'node:assert/strict';
import {micro,remaining} from './money.mjs';
import {reserve,settle,release,markUncertain} from './budget-ledger.mjs';
const ledger=()=>({budgets:['tenant','venture','scan'].map(id=>({id,currency:'USD',limit:'1000000',settled:'0',reserved:'0',paused:false})),reservations:[]});
const cmd={operationKey:'capture-1',requestHash:'canonical-hash-1',amount:'30000',currency:'USD',budgetIds:['tenant','venture','scan'],requiredBudgetIds:['tenant','venture','scan']};
for(const x of ['-1','0.03','01','','NaN','1e6','1000000000000000',3,null])test(`reject noncanonical micro ${String(x)}`,()=>assert.throws(()=>micro(x)));
test('exact micro arithmetic has no floating-point error',()=>assert.equal(micro('30000')+micro('30000'),60000n));
test('balance can expose a negative overrun honestly',()=>assert.deepEqual(remaining({limit:'100',settled:'120',reserved:'0'}),{amount:'-20',overrun:true}));
test('reservation applies to every scope, input is immutable',()=>{const l=ledger(),r=reserve(l,cmd);assert.ok(r.ledger.budgets.every(b=>b.reserved==='30000'));assert.equal(l.reservations.length,0)});
test('repeated operation does not reserve again',()=>{const a=reserve(ledger(),cmd);const b=reserve(a.ledger,cmd);assert.equal(b.replayed,true);assert.equal(b.ledger.reservations.length,1)});
test('changed operation data conflicts',()=>{const a=reserve(ledger(),cmd);assert.throws(()=>reserve(a.ledger,{...cmd,amount:'1'}),e=>e.code==='IDEMPOTENCY_CONFLICT')});
test('omitted parent cap rejected',()=>assert.throws(()=>reserve(ledger(),{...cmd,budgetIds:['scan']}),e=>e.code==='MISSING_BUDGET'));
test('duplicate budget IDs rejected',()=>assert.throws(()=>reserve(ledger(),{...cmd,budgetIds:['scan','scan']})));
test('missing known scope rejected',()=>{const l=ledger();l.budgets.pop();assert.throws(()=>reserve(l,cmd),e=>e.code==='UNKNOWN_BUDGET')});
test('one parent paused blocks all work',()=>{const l=ledger();l.budgets[0].paused=true;assert.throws(()=>reserve(l,cmd),e=>e.code==='BUDGET_PAUSED')});
test('currency mismatch cannot convert silently',()=>{const l=ledger();l.budgets[1].currency='EUR';assert.throws(()=>reserve(l,cmd),e=>e.code==='CURRENCY_MISMATCH')});
test('lowest cap blocks and leaves input untouched',()=>{const l=ledger();l.budgets[2].limit='20000';assert.throws(()=>reserve(l,cmd),e=>e.code==='BUDGET_EXCEEDED');assert.equal(l.budgets[0].reserved,'0')});
test('sequential admissions account for existing reservations',()=>{const a=reserve(ledger(),{...cmd,amount:'990000'});assert.throws(()=>reserve(a.ledger,{...cmd,operationKey:'other'}),e=>e.code==='BUDGET_EXCEEDED')});
test('settle reduces whole reserve and adds only actual',()=>{const a=reserve(ledger(),cmd);const b=settle(a.ledger,{operationKey:cmd.operationKey,actual:'20000'});assert.ok(b.ledger.budgets.every(x=>x.reserved==='0'&&x.settled==='20000'))});
test('settlement replay is no-op',()=>{const a=settle(reserve(ledger(),cmd).ledger,{operationKey:cmd.operationKey,actual:'20000'});assert.equal(settle(a.ledger,{operationKey:cmd.operationKey,actual:'20000'}).replayed,true)});
test('different settlement amount conflicts',()=>{const a=settle(reserve(ledger(),cmd).ledger,{operationKey:cmd.operationKey,actual:'20000'});assert.throws(()=>settle(a.ledger,{operationKey:cmd.operationKey,actual:'30000'}),e=>e.code==='IDEMPOTENCY_CONFLICT')});
test('unexpected actual overrun recorded and pauses all budgets',()=>{const a=settle(reserve(ledger(),cmd).ledger,{operationKey:cmd.operationKey,actual:'2000000'});assert.equal(a.overrun,true);assert.ok(a.ledger.budgets.every(x=>x.paused&&x.settled==='2000000'))});
test('uncertain call retains its reservation',()=>{const a=markUncertain(reserve(ledger(),cmd).ledger,cmd.operationKey);assert.equal(a.reservations[0].state,'uncertain');assert.equal(a.budgets[0].reserved,'30000')});
test('cancellation alone cannot release unknown cost',()=>assert.throws(()=>release(reserve(ledger(),cmd).ledger,{operationKey:cmd.operationKey,confirmedNoCharge:false}),e=>e.code==='RECONCILIATION_REQUIRED'));
test('confirmed uncharged reservation releases without settled cost',()=>{const a=release(reserve(ledger(),cmd).ledger,{operationKey:cmd.operationKey,confirmedNoCharge:true});assert.ok(a.budgets.every(x=>x.reserved==='0'&&x.settled==='0'))});
test('uncertain cost can settle after reconciliation',()=>{const a=markUncertain(reserve(ledger(),cmd).ledger,cmd.operationKey);assert.equal(settle(a,{operationKey:cmd.operationKey,actual:'30000'}).ledger.reservations[0].state,'settled')});
test('settled money cannot be released',()=>{const a=settle(reserve(ledger(),cmd).ledger,{operationKey:cmd.operationKey,actual:'20000'});assert.throws(()=>release(a.ledger,{operationKey:cmd.operationKey,confirmedNoCharge:true}),e=>e.code==='INVALID_TRANSITION')});
test('released operation cannot settle',()=>{const a=release(reserve(ledger(),cmd).ledger,{operationKey:cmd.operationKey,confirmedNoCharge:true});assert.throws(()=>settle(a,{operationKey:cmd.operationKey,actual:'1'}),e=>e.code==='INVALID_TRANSITION')});
